### ISSUE TITLE
Problem with HelloWorld application (get image from the webcam + show it on the display)

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualCircuit#137]
![helloworld-vc](https://user-images.githubusercontent.com/10961573/159858946-184c2380-bfc1-43da-ba75-1b7bf8a19146.png)

This simple application is failing on my computer (Ubuntu Linux 20.04, python 3.8.10). I'm using current release of VisualCircuit available at [https://visualcircuit.org/](https://visualcircuit.org/). It seems a problem with the wire backend, doesn't it?

```
jmplaza@papagena:~/research/fpgas$ python3 main.py 
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jmplaza/research/fpgas/modules/Camera100.py", line 10, in loop
    output_0 = share_image(output_wires[0])
IndexError: list index out of range
Waiting for Block Input...
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jmplaza/research/fpgas/modules/Screen100.py", line 10, in loop
    input_0 = read_image(input_wires[0])
IndexError: list index out of range
Waiting for Block Input...
Waiting for Block Input...
Waiting for Block Input...
```
Any idea?

**Comment by AbsorbedInThought** [comment]
I tried it right now and it seems to be working for me:
![image](https://user-images.githubusercontent.com/37846193/159888469-c7530aa4-9978-4e4f-8513-1c263ac6f8b8.png)

Does the PyQt5 window show up when you run the code?

If not, install these. There were some changes in PyQt5.
sudo apt-get install -y libxcb-xinerama0
pip install --upgrade pyqt5


Can you share your data.json file in the project folder? It seems like the wire mapping wasn't provided correctly from the frontend.

**Comment by jmplaza** [comment]
Yes @AbsorbedInThought , the PyQt5 window appeared. You were right there was a bad wire mapping, the blocks were not properly connected. The "wires" section in the data.json was empty.

Now I've made sure it they both are properly connected, the wires section now has contents. And it now works like a charm :-)

Thanks!

![helloworld](https://user-images.githubusercontent.com/10961573/159900093-74ace1be-5a25-4e2f-9168-c4f08b0a7746.png)
