### ISSUE TITLE
localhost returns compilation error 

### ISSUE THREAD

**Issue by shubhangi013** [JdeRobot/VisualCircuit#140]
While running the application on my local system, I got the following error in the browser.
![Screenshot from 2022-04-05 19-52-20](https://user-images.githubusercontent.com/78342516/161776147-d7e2b871-2846-406c-bc5f-45d49263cbf8.png)

It is a common problem, with the latest stable node release. I solved it by uninstalling node-sass and then installing sass. Since it is common problem, I think there should be troubleshooting instructions in the readme. I can add those.
I was able to run it afterwards:
![Screenshot from 2022-04-05 20-06-06](https://user-images.githubusercontent.com/78342516/161778565-2d0a9fa9-9b44-4114-900f-93f034adda4a.png)

**Comment by toshan-luktuke** [comment]
Had the same issue as well, it looks like `node-sass` is deprecated and the developers advise moving to Dart `sass`.
Found [this](https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0) stackoverflow link about it.
One way to fix it is by running:

**Comment by shubhangi013** [comment]
> Had the same issue as well, it looks like `node-sass` is deprecated and the developers advise moving to Dart `sass`.
> Found [this](https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0) stackoverflow link about it.
> One way to fix it is by running:
> 1. `npm uninstall node-sass`
> 2. `npm install sass`
> 
> Alternatively changing the package.json in the frontend folder from:
> ```json
> "node-sass": "^7.0.0",
> ```
> to
> ```json
> "sass": "^1.50.0",
> ```
> will also work
> 
> 

Yep! The same worked for me. I'll open a PR giving instructions to troubleshoot this error.
