### ISSUE TITLE
ROS2?

### ISSUE THREAD

**Issue by samuk** [JdeRobot/VisualCircuit#207]
Do you have any plans to update for ROS2?

**Comment by jmplaza** [comment]
Yes, we are working on that. Take a look at [@tapi1300 's blog](https://roboticslaburjc.github.io/2022-tfg-david-tapiador/blog/15th_week/) for his progress on that. The "Follow person" application has been developed with ROS2. 

In addition, we have developed some driver blocks for ROS2 sensors and actuators, but more help on that will be great.

**Comment by samuk** [comment]
Thanks, will take a look

**Comment by jmplaza** [comment]
https://www.youtube.com/watch?v=IknpvAs_jAo
