### ISSUE TITLE
Nested blocks are not possible

### ISSUE THREAD

**Issue by tapi1300** [JdeRobot/VisualCircuit#215]
I have recently faced a problem while trying to develop a state machine.
If i try to create a complex block made of more nested blocks inside it, the only blocks that actually come in the build zip are the external ones (not containing the nested ones).

[Here](https://roboticslaburjc.github.io/2022-tfg-david-tapiador/blog/21th_week/) is my TFG blog where I explain the problem better. 

And here is a screenshot of the actual output (after unzipping) of the build process.
![Screenshot from 2023-05-11 20-35-17](https://github.com/JdeRobot/VisualCircuit/assets/60138776/b1ac46ee-c0e5-4a53-8b18-3a1135f29595)

**Comment by Suhas-G** [comment]
Hello, can you please attach the .vc file? It will be easier for me to debug. Thanks

**Comment by tapi1300** [comment]
This is the project as it came out by using "Build and Download", inside of it you can find the .vc3 file.

[FSM.zip](https://github.com/JdeRobot/VisualCircuit/files/11556244/FSM.zip)

**Comment by Suhas-G** [comment]
Thanks. I will try to fix it over the weekend.

**Comment by BkPankaj** [comment]
@tapi1300 @Suhas-G The issue has been resolved with PR #325. Please verify it on your end. For now, I am closing this issue as it has been verified by me and @toshan-luktuke. If there are still any issues, kindly provide your feedback in the comments.
