### ISSUE TITLE
postinstall script in pacakge.json file

### ISSUE THREAD

**Issue by shreyas2000** [JdeRobot/VisualCircuit#73]
1) The script contains "npmpd" command which is not a npm command which freezes the script.
2)Bower install is not working in app folder 
3)There is no folder named tasks so "cd ../tasks" is failing.

Due to which npm start is not working and Visual circuit is not starting.
I think this script belongs to icestudio's  pacakage.json file.

**Comment by AbsorbedInThought** [comment]
You can use the packaged release for linux64 for now, which can be found here: 
https://github.com/JdeRobot/VisualCircuit/releases/tag/v2.1.0

There are some changes that I have to commit in the repository, hopefully this will be fixed in a few days. Thanks for pointing it out!

**Comment by shreyas2000** [comment]
Hi,
I downloaded [Source code(zip)](https://github.com/JdeRobot/VisualCircuit/archive/refs/tags/v2.1.0.zip) from the link you mentioned above and got the error i mentioned in first comment.
There are 3 files present there . Can you plaese tell me which one should i download.
Thank you!

**Comment by AbsorbedInThought** [comment]
You should download the .AppImage and simply run it. Also, run this script to install the required dependencies:
https://github.com/JdeRobot/VisualCircuit/blob/master/requirements.sh

My local installation of VisualCircuit is around 6GB right now. I had to remove a lot of dependencies from the release that are required to install VisualCircuit for development.

**Comment by shreyas2000** [comment]
Can we package the dependencies in a docker image and simply use it to run the tool to avoid running multiple commands and installations. It will be easier while migrating to web version.
Also should i update the above changes in usermanual.md as instructions mentioned there are different.

**Comment by AbsorbedInThought** [comment]
Yeah, a docker image would be better.
Feel free to create an issue and update the usermanual.md or add any relevant info that you think might be important for installation.
