### ISSUE TITLE
Integrate React with Django

### ISSUE THREAD

**Issue by Shahmirtk** [JdeRobot/VisualCircuit#85]
Integrate the frontend server running React with a backend server running Django.

**Comment by jmplaza** [comment]
I would start with a very basic React webpage, not the current VisualCircuit-3 frontend

**Comment by Shahmirtk** [comment]
Sure.

**Comment by sandnb** [comment]
Hello, May I know if someone still working on this issue?

**Comment by Shahmirtk** [comment]
Not me.
